---
output:
    mintr::mint_handout
---

```{r, setup, cache=FALSE, message=FALSE, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)
library(dplyr)
library(ggplot2)

opts_chunk$set(cache=FALSE, message=FALSE, echo=FALSE, warning=FALSE, results='asis')

knit_hooks$set(inline = function(x) {
  if (is.numeric(x)) round(x, 1)})

options("guiToolkit" = "tcltk")
# options("guiToolkit" = "RGtk2")
w <- gWidgets::gbasicdialog(title = "Connection status", do.buttons = T, handler = function(h, ...)
  online <<- gWidgets::svalue(selection))
selection <- gWidgets::gcombobox(c("Offline", "Online"), editable = F, expand = T, container = w)
gWidgets::visible(w, set = T) ## show dialog
```

```{r, prepare_data, results='hide'}
if(online %in% 'Online'){
  devtools::source_url("https://raw.githubusercontent.com/jpolonsky/disastr/master/print.xtable.R")
  devtools::source_url("https://raw.githubusercontent.com/jpolonsky/disastr/master/prepare_data.R")
} else {
  
  source(system.file('code/print.xtable.R', package = 'mintr'))
  
  wb <- disastr::fileChoose()
  listSheets <- readxl::excel_sheets(wb)
  
  w <- gWidgets::gbasicdialog(title = "Select year of interest", do.buttons = T, handler = function(h, ...)
    year <<- gWidgets::svalue(selection))
  selection <- gWidgets::gcombobox(c("2014", "2015"), editable = T, expand = T, container = w)
  gWidgets::visible(w, set = T) ## show dialog
  
  df_raw <- readxl::read_excel(wb, sheet = listSheets[grep("Contribution", listSheets)], skip = 1)
  df_extra <- readxl::read_excel(wb, sheet = listSheets[grep(paste0("ctrbns ", year), listSheets)], skip = 1)
  df_filter <- readxl::read_excel(wb, sheet = listSheets[grep(paste0("SRP ", year), listSheets)], skip = 2)
  
  # tmpList <- list(df_raw, df_extra, df_filter)
  # Map(excludeEmpty, tmpList) ## returns list of dataframes with excluded empty columns
  
  df_raw <- disastr::excludeEmpty(df_raw)
  df_extra <- disastr::excludeEmpty(df_extra)
  df_filter <- disastr::excludeEmpty(df_filter)
  
  ## Create lists of variables of interest
  list_var <- c('Recipient country', 'Donor', 'Type of appeal issued', 'Amount in US$')
  
  ## Restrict dataframe to variables of interest
  df_selectionx <- df_raw[, list_var]
  names(df_selectionx) <- c('country', 'donor', 'appeal', 'amount_received')

  df_extra <- df_extra[df_extra$Status %in% 'Contribution', c(3, 5, 7, 9)]
  names(df_extra) <- c('country', 'donor', 'appeal', 'amount_received')

  df_selection <- rbind(df_selectionx, df_extra)

  names(df_filter) <- c('appeal', 'status', 'amount_requested')

  ## Merge datasets to restrict to appeals of interest
  df <- merge(df_filter, df_selection)

  list_status <- factor(c('L3', 'L2', 'Priority', 'Other'))
  list_country <- sort(unique(df$country))
  list_donor <- sort(unique(df$donor))
  list_appeal <- sort(unique(df$appeal))
  
  df_donor <-
    df %>%
    group_by(appeal, status, donor) %>%
    summarise(total_requested = min(amount_requested, na.rm = T),
              total_received = sum(amount_received, na.rm = T),
              prop_funded = round(sum(amount_received, na.rm = T)/min(amount_requested, na.rm = T)*100, digits = 1)) %>%
    arrange(status, appeal, desc(total_received))
  
  df_donor$prop_funded <- ifelse(df_donor$prop_funded == Inf, 100, df_donor$prop_funded)
  df_donor$prop_funded[is.na(df_donor$prop_funded)] <- 0
  
  df_total <-
    df %>%
    group_by(appeal, status) %>%
    summarise(total_requested = min(amount_requested, na.rm = T),
              total_received = sum(amount_received, na.rm = T),
              prop_funded = round(sum(amount_received, na.rm = T)/min(amount_requested, na.rm = T)*100, digits = 1)) %>%
    arrange(desc(prop_funded), status, appeal)
  
  df_total$prop_funded <- ifelse(df_total$prop_funded == Inf, 100, df_total$prop_funded)
  df_total$prop_funded[is.na(df_total$prop_funded)] <- 0
  
  df_total$status <- factor(df_total$status, levels = c('L3', 'L2', 'Priority', 'Other'))
  df_total <- arrange(df_total, desc(prop_funded))
  df_total <- df_total %>% filter(!is.na(status))
  
  list_appeals_L3 <- sort(unique(df_total$appeal[df_total$status == 'L3']))
  list_appeals_priority <- sort(unique(df_total$appeal[df_total$status == 'Priority']))
  list_appeals_other <- sort(unique(df_total$appeal[df_total$status == 'Other']))
  
  df_total$appeal <- factor(df_total$appeal, levels = df_total$appeal)
  
}
```

```{r, tab_overview}
df_total$status <- factor(df_total$status, levels = c('L3', 'L2', 'Priority', 'Other'))
df_total <- df_total[order(df_total$status, desc(df_total$prop_funded)), ]
names(df_total) <- c('Appeal', 'Crisis type', 'Amount requested', 'Amount received', 'Funded (%)')

if(nrow(df_total)>1) {rws <- seq(1, nrow(df_total) - 1, by = 2)}

col <- rep("\\rowcolor{whoblue!15}", length(rws))

z <- xtable::xtable(disastr::separator(df_total), caption = 'Overview of amounts donated/firmly pledged as a percentage of total requested, by appeal', digits = 0, label = "tab_overview")

xtable::align(z) <- 'lllrrr'

print(z, type = 'latex', booktabs = T, caption.placement = "top", add.to.row = list(pos = as.list(rws), command = col), include.rownames=FALSE, scalebox=1)
```

```{r, fig_pop, fig.cap='Overview of amounts donated/firmly pledged as a percentage of total requested, by appeal', fig.pos='!htbp', fig.height=4.5}
disastr::PlotBar(data = df_total, xvar = 'Appeal', yvar = 'Funded (%)', yaxis = 'Funded (%)')
```

```{r, table_loop}
df_donor <- as.data.frame(df_donor)

for (j in list_status) {
  cat(paste0("\\clearpage\n"))
  
  if(j == 'L3') {
    cat(paste0("\\section{Grade 3 emergencies}\n"))
  } else if (j == 'L2') {
    cat(paste0("\\section{Grade 2 emergencies}\n"))
  } else if (j == 'Priority') {
    cat(paste0("\\section{Priority countries}\n"))
  } else {
    cat(paste0("\\section{Other appeals}\n"))
  }
  
  for (i in df_filter$appeal[df_filter$status %in% j]) {
    cat(paste0("\\subsection{", i, "}\n"))
    
    
    df_selected <- df_donor[df_donor$status %in% j & df_donor$appeal %in% i, ][, c(3, 5, 6)]
    
    names(df_selected) <- c('Donor', 'Amount received', 'Funded (%)')
    
    total_col <- colSums(df_selected[, c(2, 3)])
    total_colx <- c(0, total_col)
    names(total_colx) <- c('Donor', 'Amount received', 'Funded (%)')
    total_colx[3] <- ifelse(total_colx[3]>100, '-', total_colx[3])
    
    df_selected <- rbind(df_selected, total_colx)
    
    # levels(df_selected$Donor) <- c(levels(df_selected$Donor), 'TOTAL', 'None')
    df_selected$Donor[nrow(df_selected)] <- 'TOTAL'
    
    df_selected[, 2] <- as.numeric(df_selected[, 2])
    
    # df_selected$Donor[df_selected$Donor %in% ''] <- 'None'
    df_selected$Donor[is.na(df_selected$Donor)] <- 'None'
    
    if(nrow(df_selected)>1) {rws <- seq(1, nrow(df_selected) - 1, by = 2)}
    
    col <- rep("\\rowcolor{whoblue!15}", length(rws))
    
    z <- xtable::xtable(disastr::separator(df_selected), caption = paste0('Overview of amounts donated/firmly pledged as a percentage of total requested: ', i), digits = 0, label = paste0('tab_', i))
    
    comment          <- list()
    comment$pos      <- list()
    comment$pos[[1]] <- c(nrow(z))
    
    if(df_donor[df_donor$status %in% j & df_donor$appeal %in% i, ][1, 4] %in% 0) {
      comment$command  <- c(paste0("\\hline \n\\emph{\\footnotesize{\\textcolor{red}{N.B. No funding requirements established against this appeal.}}}\n"))
    } else {
      comment$command  <- c(paste0("\\hline \n\\emph{\\footnotesize{Amount requested: US\\$ ", disastr::separator(df_donor[df_donor$status %in% j & df_donor$appeal %in% i, ][1, 4]),"}}\n"))
    }
    
    xtable::align(z) <- 'llrr' # to be used with: tabular.environment="tabularx"
    
    #print(z, type = 'latex', floating='F', table.placement="!htp", booktabs = T, caption.placement = "top", include.rownames=FALSE, latex.environments="center", add.to.row = comment, hline.after = c(-1, 0))
    
    print(z, type = 'latex', floating='F', table.placement="!htp", booktabs = T, caption.placement = "top", include.rownames=FALSE, latex.environments="center", add.to.row = list(pos = as.list(rws), command = col))
    
    if(df_donor[df_donor$status %in% j & df_donor$appeal %in% i, ][1, 4] %in% 0) {
      cat(paste0("\n\\emph{\\footnotesize{\\textcolor{red}{N.B. No funding requirements established against this appeal}}}\n"))
    } else {
      cat(paste0("\n\\emph{\\footnotesize{Amount requested: US\\$ ", disastr::separator(df_donor[df_donor$status == j & df_donor$appeal == i, ][1, 4]),"}}\n"))
    }
    
  }
  
}
```

